host: "127.0.0.1"
port: "8085"
client_id: "yourAzureClientID" # Azure App registration client ID
tenant_id: "yourAzureTenantID" # Azure tenant ID
proxy_url: "https://outlook.office365.com"
authority_url: "https://login.microsoftonline.com/"
scopes:
  - "https://outlook.office365.com/EWS.AccessAsUser.All"
